kind = "api"
  previewPath = "/bk-api/"
  title = "API Server"
  version = "1.0.0"
  id = "3B4_FFSkEVBkAeYMFRJ2e"

  [[services]]
  localPort = 18080
  name = "API Server"
  paths = ["/bk-api/"]

  [services.development]
  run = "echo backup-disabled"
  